apiVersion: v1
kind: Service
metadata:
  name: k8s-agent
  namespace: default
spec:
  selector:
    app: k8s-agent
  ports:
    - port: 8000
      targetPort: 8000 
      nodePort: 31990
  type: NodePort
