apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: agent-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: agent-clusterrole
  apiGroup: rbac.authorization.k8s.io
