apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-clusterrole
rules:
  # akses semua namespace
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # akses deployment di semua namespace
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
